// Mocks generated by Mockito 5.4.6 from annotations
// in app_sodimac_test/test/features/cart/data/repositories/cart_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_sodimac_test/features/cart/data/datasources/cart_local_datasource.dart'
    as _i2;
import 'package:app_sodimac_test/features/cart/data/models/cart_item_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CartLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartLocalDataSource extends _i1.Mock
    implements _i2.CartLocalDataSource {
  MockCartLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CartItemModel>> getCartItems() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItems, []),
            returnValue: _i3.Future<List<_i4.CartItemModel>>.value(
              <_i4.CartItemModel>[],
            ),
          )
          as _i3.Future<List<_i4.CartItemModel>>);

  @override
  _i3.Future<_i4.CartItemModel?> getCartItem(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getCartItem, [productId]),
            returnValue: _i3.Future<_i4.CartItemModel?>.value(),
          )
          as _i3.Future<_i4.CartItemModel?>);

  @override
  _i3.Future<void> addToCart(_i4.CartItemModel? item) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateQuantity(String? productId, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [productId, quantity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [productId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getCartItemCount() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItemCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<double> getCartTotal() =>
      (super.noSuchMethod(
            Invocation.method(#getCartTotal, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);
}
